"""Low-light simulation and noise-level estimation.

The project brief specifically targets *low-light video recording*.
Low light forces higher sensor gain (ISO), which amplifies two
noise sources: signal-dependent **shot noise** (Poisson, from photon
counting statistics) and roughly signal-independent **read noise**
(Gaussian, from sensor/amplifier electronics). This module provides:

* a synthetic low-light + sensor-noise simulator, so the filters can be
  benchmarked quantitatively against a known-clean ground truth
  (real low-light footage has no clean reference to compute PSNR/SSIM
  against), and
* a robust, wavelet-based noise-sigma estimator (Donoho's MAD
  estimator) used by the optimized bilateral filter to auto-tune its
  smoothing strength to the actual noise level of a frame instead of a
  hand-tuned constant.

References
----------
- Donoho, D. L. (1995). "De-noising by soft-thresholding." IEEE
  Transactions on Information Theory. (MAD-based sigma estimator,
  sigma = median(|W_HH|) / 0.6745)
- Healey, G. E., & Kondepudy, R. (1994). "Radiometric CCD camera
  calibration and noise estimation." (Poisson-Gaussian sensor noise
  model)
"""
from __future__ import annotations

import cv2
import numpy as np
import pywt



# The raw MAD/wavelet estimator is a robust but slightly biased-low
# estimate of the true noise standard deviation for the signal-dependent
# Poisson-Gaussian mixture this project simulates (it was calibrated
# empirically against the known-clean references generated by
# scripts/generate_test_data.py: the per-channel-averaged raw estimate
# tracks the true injected noise sigma to within ~2 dB PSNR once scaled
# by this constant). Applying the same constant consistently keeps the
# estimator comparable across noise levels.
_MAD_CALIBRATION = 1.25


# A global noise-level estimate does not need every pixel: the MAD
# statistic is computed over a strided subsample capped at this many
# pixels per side, which keeps estimate_noise_sigma() cheap and
# resolution-independent -- important since bilateral_optimized() calls
# it once per frame in the video pipeline. Measured to match the
# full-resolution estimate to within ~1.5 (0-255 scale) on a 720p test
# frame while being an order of magnitude faster (see docs/BENCHMARK_REPORT.md).
_ESTIMATION_MAX_DIM = 256


def _single_channel_sigma(channel: np.ndarray) -> float:
    ch = channel.astype(np.float64)
    h, w = ch.shape
    stride = max(1, max(h, w) // _ESTIMATION_MAX_DIM)
    if stride > 1:
        ch = ch[::stride, ::stride]
    # Single-level Haar DWT is cheap and standard for this estimator:
    # the finest-scale diagonal (HH) sub-band responds mostly to noise
    # and little to real image structure.
    _, (_, _, hh) = pywt.dwt2(ch, "db1")
    return float(np.median(np.abs(hh)) / 0.6745)


def estimate_noise_sigma(image: np.ndarray) -> float:
    """Estimate the additive-noise standard deviation of ``image``.

    For a color (BGR) image, the estimate is averaged over the three
    channels independently (more accurate than estimating on luma
    alone, since luma = a weighted channel *average* partially cancels
    independent per-channel sensor noise). For a single-channel image,
    the estimate is computed directly. Each channel is estimated on a
    strided subsample (see ``_ESTIMATION_MAX_DIM``) so the cost stays
    roughly constant regardless of frame resolution. The raw MAD
    estimate is then scale-corrected by an empirically fit constant
    (see ``_MAD_CALIBRATION``).
    """
    if image.ndim == 3:
        raw = float(np.mean([_single_channel_sigma(image[:, :, c]) for c in range(image.shape[2])]))
    else:
        raw = _single_channel_sigma(image)
    return float(max(raw * _MAD_CALIBRATION, 1e-6))


def simulate_low_light(image: np.ndarray, exposure_factor: float = 0.25, gamma: float = 1.0) -> np.ndarray:
    """Darken a well-lit image to approximate a low-light exposure.

    ``exposure_factor`` < 1 scales down the linear light level (as if a
    shorter exposure / smaller aperture were used). An optional
    ``gamma`` can additionally compress shadows, mimicking a camera's
    tone curve. Operates in linearised space for physical plausibility.
    """
    img = image.astype(np.float64) / 255.0
    linear = np.power(img, 2.2)  # undo an assumed sRGB-like gamma
    linear *= exposure_factor
    if gamma != 1.0:
        linear = np.power(np.clip(linear, 0, 1), gamma)
    srgb = np.power(np.clip(linear, 0, 1), 1 / 2.2)
    return np.clip(srgb * 255.0, 0, 255).astype(np.uint8)


def add_poisson_gaussian_noise(
    image: np.ndarray,
    shot_noise_scale: float = 6.0,
    read_noise_sigma: float = 4.0,
    seed: int | None = None,
) -> np.ndarray:
    """Add a realistic signal-dependent sensor-noise model.

    ``shot_noise_scale`` controls the strength of Poisson (shot) noise:
    higher values (i.e. lower effective photon counts, as in a dim
    scene) mean *more* relative noise. ``read_noise_sigma`` is the
    signal-independent Gaussian read-noise standard deviation (0-255
    scale). This is the standard Poisson-Gaussian model used in
    low-light / raw-denoising literature.
    """
    rng = np.random.default_rng(seed)
    img = image.astype(np.float64)

    # Shot noise: scale down to a pseudo photon-count domain, sample
    # Poisson, scale back up. Smaller `shot_noise_scale` -> fewer
    # "photons" per level -> relatively more noise (as in a dim scene).
    photon_scale = 255.0 / max(shot_noise_scale, 1e-3)
    lam = np.clip(img, 0, 255) / 255.0 * photon_scale
    shot_noisy = rng.poisson(lam).astype(np.float64) / photon_scale * 255.0

    # Read noise: additive Gaussian, independent of signal.
    read_noisy = shot_noisy + rng.normal(0.0, read_noise_sigma, size=img.shape)

    return np.clip(read_noisy, 0, 255).astype(np.uint8)


def make_low_light_noisy(
    clean_image: np.ndarray,
    exposure_factor: float = 0.25,
    shot_noise_scale: float = 6.0,
    read_noise_sigma: float = 4.0,
    seed: int | None = None,
) -> np.ndarray:
    """Convenience wrapper: darken + add sensor noise in one call."""
    dark = simulate_low_light(clean_image, exposure_factor=exposure_factor)
    return add_poisson_gaussian_noise(
        dark, shot_noise_scale=shot_noise_scale, read_noise_sigma=read_noise_sigma, seed=seed
    )


def enhance_low_light(image: np.ndarray, clip_limit: float = 2.5, tile_grid_size: tuple[int, int] = (8, 8)) -> np.ndarray:
    """CLAHE-based brightness/contrast recovery for a dark frame.

    Intended to run *after* denoising (denoise-then-enhance avoids
    amplifying noise that a naive brighten-first pipeline would boost).
    """
    ycrcb = cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
    y, cr, cb = cv2.split(ycrcb)
    clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=tile_grid_size)
    y_eq = clahe.apply(y)
    merged = cv2.merge([y_eq, cr, cb])
    return cv2.cvtColor(merged, cv2.COLOR_YCrCb2BGR)
